// Code generated by "stringer -type=Location"; DO NOT EDIT.

package references

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EmptyLocation-255]
	_ = x[Britannia_Underworld-0]
	_ = x[Moonglow-1]
	_ = x[Britain-2]
	_ = x[Jhelom-3]
	_ = x[Yew-4]
	_ = x[Minoc-5]
	_ = x[Trinsic-6]
	_ = x[Skara_Brae-7]
	_ = x[New_Magincia-8]
	_ = x[Fogsbane-9]
	_ = x[Stormcrow-10]
	_ = x[Greyhaven-11]
	_ = x[Waveguide-12]
	_ = x[Iolos_Hut-13]
	_ = x[Suteks_Hut-14]
	_ = x[SinVraals_Hut-15]
	_ = x[Grendels_Hut-16]
	_ = x[Lord_Britishs_Castle-17]
	_ = x[Palace_of_Blackthorn-18]
	_ = x[West_Britanny-19]
	_ = x[North_Britanny-20]
	_ = x[East_Britanny-21]
	_ = x[Paws-22]
	_ = x[Cove-23]
	_ = x[Buccaneers_Den-24]
	_ = x[Ararat-25]
	_ = x[Bordermarch-26]
	_ = x[Farthing-27]
	_ = x[Windemere-28]
	_ = x[Stonegate-29]
	_ = x[Lycaeum-30]
	_ = x[Empath_Abbey-31]
	_ = x[Serpents_Hold-32]
	_ = x[Deceit-33]
	_ = x[Despise-34]
	_ = x[Destard-35]
	_ = x[Wrong-36]
	_ = x[Covetous-37]
	_ = x[Shame-38]
	_ = x[Hythloth-39]
	_ = x[Doom-40]
	_ = x[Combat_resting_shrine-41]
}

const (
	_Location_name_0 = "Britannia_UnderworldMoonglowBritainJhelomYewMinocTrinsicSkara_BraeNew_MaginciaFogsbaneStormcrowGreyhavenWaveguideIolos_HutSuteks_HutSinVraals_HutGrendels_HutLord_Britishs_CastlePalace_of_BlackthornWest_BritannyNorth_BritannyEast_BritannyPawsCoveBuccaneers_DenAraratBordermarchFarthingWindemereStonegateLycaeumEmpath_AbbeySerpents_HoldDeceitDespiseDestardWrongCovetousShameHythlothDoomCombat_resting_shrine"
	_Location_name_1 = "EmptyLocation"
)

var (
	_Location_index_0 = [...]uint16{0, 20, 28, 35, 41, 44, 49, 56, 66, 78, 86, 95, 104, 113, 122, 132, 145, 157, 177, 197, 210, 224, 237, 241, 245, 259, 265, 276, 284, 293, 302, 309, 321, 334, 340, 347, 354, 359, 367, 372, 380, 384, 405}
)

func (i Location) String() string {
	switch {
	case i <= 41:
		return _Location_name_0[_Location_index_0[i]:_Location_index_0[i+1]]
	case i == 255:
		return _Location_name_1
	default:
		return "Location(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
